# Generated by Django 4.0.6 on 2022-08-16 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0002_attendance_course_enrollmet_student_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('option_1', models.CharField(max_length=200, null=True)),
                ('option_2', models.CharField(max_length=200, null=True)),
                ('option_3', models.CharField(max_length=200, null=True)),
                ('option_4', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('question_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dataservice.course')),
                ('quiz', models.ManyToManyField(to='dataservice.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='dataservice.course')),
            ],
        ),
    ]
