# Generated by Django 4.0.6 on 2022-08-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0003_quiz_questions_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='subject',
        ),
    ]
