# Generated by Django 4.0.6 on 2022-08-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0004_remove_questions_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
    ]
