# Generated by Django 4.0.6 on 2022-08-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0005_remove_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_mark',
        ),
        migrations.AddField(
            model_name='questions',
            name='Total_mark',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
