# Generated by Django 4.0.6 on 2022-08-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataservice.quiz'),
        ),
    ]
