# Generated by Django 4.0.6 on 2022-08-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0009_remove_questions_quiz_alter_questions_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dataservice.quiz'),
        ),
    ]
