# Generated by Django 4.0.6 on 2022-08-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0012_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmet',
            unique_together={('student', 'course')},
        ),
    ]
