# Generated by Django 4.0.6 on 2022-08-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0013_alter_enrollmet_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmet',
            unique_together=set(),
        ),
    ]
