# Generated by Django 4.0.6 on 2022-08-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0014_alter_enrollmet_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmet',
            unique_together={('student', 'course')},
        ),
    ]
